### ISSUE TITLE
[Question] Latest SonarQube server compatible with the ResharperPlugin ?

### ISSUE THREAD

**Issue by cnaslain** [GregBartlett/sonar-resharper#36]
Hi,

I've tries to install the ReSharper Plugin into the Community EditionVersion 7.4 (build 18908) and got the following error. I guess, as the ReSharper plugin is now marked as deprecated, that it cannot anylonger be installed into the latest version?
Do you know what was the latest Sonar Server version that was accepting this plugin?

2018.10.31 10:19:06 INFO  web[][o.s.s.a.EmbeddedTomcat] HTTP connector enabled on port 9000
2018.10.31 10:19:07 ERROR web[][o.s.s.p.Platform] Background initialization failed. Stopping SonarQube
java.lang.IllegalStateException: Fail to load plugin ReSharper [resharper]
	at org.sonar.server.plugins.ServerExtensionInstaller.installExtensions(ServerExtensionInstaller.java:82)
	at org.sonar.server.platform.platformlevel.PlatformLevel4.start(PlatformLevel4.java:586)
	at org.sonar.server.platform.Platform.start(Platform.java:211)
	at org.sonar.server.platform.Platform.startLevel34Containers(Platform.java:185)
	at org.sonar.server.platform.Platform.access$500(Platform.java:46)
	at org.sonar.server.platform.Platform$1.lambda$doRun$0(Platform.java:119)
	at org.sonar.server.platform.Platform$AutoStarterRunnable.runIfNotAborted(Platform.java:371)
	at org.sonar.server.platform.Platform$1.doRun(Platform.java:119)
	at org.sonar.server.platform.Platform$AutoStarterRunnable.run(Platform.java:355)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError: com/google/common/collect/ImmutableList
	at org.sonar.plugins.resharper.ReSharperPlugin.getExtensions(ReSharperPlugin.java:52)
	at org.sonar.api.SonarPlugin.define(SonarPlugin.java:51)
	at org.sonar.server.plugins.ServerExtensionInstaller.installExtensions(ServerExtensionInstaller.java:72)
	... 9 common frames omitted
Caused by: java.lang.ClassNotFoundException: com.google.common.collect.ImmutableList
	at org.sonar.classloader.ParentFirstStrategy.loadClass(ParentFirstStrategy.java:39)
	at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:87)
	at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:76)
	... 12 common frames omitted
2018.10.31 10:19:08 INFO  web[][o.s.p.StopWatcher] Stopping process

Thanks for the feedback,
Regards,
Chris

**Comment by GregBartlett** [comment]
It was back in version 4.  Sonarqube has changed so much since then that this plugin pretty much needs a rewrite, but there hasn’t been a lot of requests to make this work with the new versions of sonar ;(

**Comment by rupreck** [comment]
It works with the version 6 LTS editions but not with the version 7 editions so it can't be too far different.

The message is: "API compatibility mode is no longer supported. In case of error, plugin ReSharper [resharper] should package its dependencies."

We would really like to see it working with the version 7 editions!

**Comment by GregBartlett** [comment]
Right, problem is you start updating the API from 4.5 or whatever it is now, there is a ton of deprecation.

 

I’ll look into getting something together on 7 in the future.

**Comment by rupreck** [comment]
Hi Greg - Have you had a chance to look at this?  It would be great to see it working on the latest edition.

**Comment by rupreck** [comment]
Hi Greg - the 7.9 LTS version has been released now. If you were to upgrade, compatibility just with that would be most appreciated.

**Comment by GregBartlett** [comment]
I’m looking at a complete rewrite.  They’ve changed sonar SOOOO much since the days of 4.5 or 5.4 or whatever this thing was compatible with.  

I started a new job this year that is a lot less stressful, I should be able to start looking at this.   Hopefully sonarqubes documentation is better now.

**Comment by rupreck** [comment]
Hi Greg,

Thanks for the reply.

I would like to assist you with this, do you have a direct contact?

David
